--- 
- hosts: all
  remote_user: ec2-user
  become: yes
  tasks: 
  - name: "Install apache httpd"
    yum:
      name: httpd
      state: latest
  - name: "Install git"
    yum:
      name: git
      state: latest
  - name: "Git checkout"
    ansible.builtin.git: 
      dest: "./ws/"
      repo: "https://github.com/ronaksuchak/interview.git"
      update: false
    name: "Git checkout"
  - name: "Ansible copy file to remote server" 
    copy: 
      remote_src: yes
      dest: /var/www/http
      src: ./ws/interview/devops-task/src 
  - name: Restart service httpd, in all cases
    service:
      name: httpd
      state: restarted
