--- 
- hosts: all
  remote_user: ec2-user
  tasks: 
  - name: "Install apache httpd"
    yum:
      name: httpd
      state: latest
    name: "Install apache httpd"
  - name: "Git checkout"
    ansible.builtin.git: 
      dest: "."
      repo: "https://github.com/ronaksuchak/interview.git"
      update: false
    name: "Git checkout"
  - name: "Ansible copy file to remote server" 
    copy: 
      dest: /var/www/http
      src: interview/devops-task/src 
